// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5K1F_rHstAyRYmfKr_OIFuxTkXbnzPzI',
    appId: '1:616311737683:web:557a600faa866d398c25a6',
    messagingSenderId: '616311737683',
    projectId: 'golf-mobile-backend',
    authDomain: 'golf-mobile-backend.firebaseapp.com',
    storageBucket: 'golf-mobile-backend.firebasestorage.app',
    measurementId: 'G-MDB9YWBT7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzIPpiwify7tWoBTYAmCq9X6ncFOEVfdk',
    appId: '1:616311737683:android:695aa5a3e8cc30cb8c25a6',
    messagingSenderId: '616311737683',
    projectId: 'golf-mobile-backend',
    storageBucket: 'golf-mobile-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDksU6bvFEIyQcyvLYxHyw7xzNwU70pzww',
    appId: '1:616311737683:ios:b4db2b1504c79c998c25a6',
    messagingSenderId: '616311737683',
    projectId: 'golf-mobile-backend',
    storageBucket: 'golf-mobile-backend.firebasestorage.app',
    iosBundleId: 'com.example.golfMobileFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDksU6bvFEIyQcyvLYxHyw7xzNwU70pzww',
    appId: '1:616311737683:ios:b4db2b1504c79c998c25a6',
    messagingSenderId: '616311737683',
    projectId: 'golf-mobile-backend',
    storageBucket: 'golf-mobile-backend.firebasestorage.app',
    iosBundleId: 'com.example.golfMobileFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5K1F_rHstAyRYmfKr_OIFuxTkXbnzPzI',
    appId: '1:616311737683:web:26c7ec854dd882528c25a6',
    messagingSenderId: '616311737683',
    projectId: 'golf-mobile-backend',
    authDomain: 'golf-mobile-backend.firebaseapp.com',
    storageBucket: 'golf-mobile-backend.firebasestorage.app',
    measurementId: 'G-G9DNSYZZ7S',
  );
}
